### ISSUE TITLE
PVA structure value change notifications

### ISSUE THREAD

**Issue by shroffk** [shroffk/phoebus#1032]
In pvaccess, when references a part of a larger structure there is a possibility that the sub structure will not have a timestamp. 

eg.
Complete Structure:

![image](https://user-images.githubusercontent.com/2111304/71022476-8e3dfb80-20ce-11ea-9914-2c0f333242bd.png)

Substructure being used in cs-studio/phoebus:

![image](https://user-images.githubusercontent.com/2111304/71022458-854d2a00-20ce-11ea-9fae-110be80e7aab.png)

When the substructure is used in Display builder...despite the fact that the value is changing, since the time stamp remains the same the widget does not update. (I am not sure if the event is not being delivered to the widget or being discarded due to the same timestamp)

Ideas:
- core-pv/pva should somehow extract the timestamp from the parent structure
- display builder, like probe should respond to value changes even when the time stamp is the same.
- we have a flag with just adds the current time stamp

**Comment by kasemir** [comment]
I don't think it's a timestamp issue. It's a matter of getting or not getting events. 
Increase the log level of org.epics.pva to FINE and check if you get "Received monitor #.. update for <channel name>" messages in one case but not the other.

**Comment by kasemir** [comment]
What are you using as a pva server? Is that something I can reproduce locally?

**Comment by shroffk** [comment]
Ok, 
Ignore the above report. After some digging the problem is not to associated with the timestamp.

The problem lies in the value comparison in the PropertyChangeHandler

```
       // Any change at all?
       if (new_value != null  &&  old_value != null  &&  new_value.equals(old_value))
           return;
```

In my case, the value is a IVDoubleArray... where the equality is checked by checking the underlying raw data points to the same array instead of looping through the array values.

```
    @Override
    public boolean equals(Object obj) {
        if (obj == this)
            return true;

        if (obj instanceof ArrayDouble) {
            ArrayDouble other = (ArrayDouble) obj;
            
            if ((array == other.array) && startIndex == other.startIndex && size == other.size)
                return true;
        }

        return super.equals(obj);
    }

```

Despite having different array values the arrays in the old and new are the same. 

![image](https://user-images.githubusercontent.com/2111304/71097545-21823a00-217e-11ea-9d29-8d6aebec952a.png)

**Comment by shroffk** [comment]
The server is available here:
https://github.com/shroffk/scope

**Comment by kasemir** [comment]
Does the array data indeed not change, so that part would be correct?

Maybe the issue here is that IVDoubleArray.equals returns True when it finds that the array data matches, instead of also checking if the alarm and time stamp match.

**Comment by kasemir** [comment]
If the data does change, you should see the debugger step into `PVADoubleArray.decode()`.
It currently keeps the array and only updates the elements as long as the array size stays the same.
I guess that's wrong. Should get a new array (as done in `setValue`) because who knows who is using that array and assumes it's the same as long as the array itself is the same.

**Comment by kasemir** [comment]
Maybe try changing this
```
    public void decode(final PVATypeRegistry types, final ByteBuffer buffer) throws Exception
    {
        final int size = PVASize.decodeSize(buffer);
        double[] new_value = value;
        if (new_value == null  ||  new_value.length != size)
            new_value = new double[size];
        for (int i=0; i<size; ++i)
            new_value[i] = buffer.getDouble();
        value = new_value;
    }
```

into this and see if that fixes it:

```
    public void decode(final PVATypeRegistry types, final ByteBuffer buffer) throws Exception
    {
        final int size = PVASize.decodeSize(buffer);
        final double[] new_value = new double[size];
        for (int i=0; i<size; ++i)
            new_value[i] = buffer.getDouble();
        value = new_value;
    }
```

**Comment by shroffk** [comment]
>I guess that's wrong. Should get a new array (as done in setValue) because who knows who is using that array and assumes it's the same as long as the array itself is the same.

Yes this is my opinion.

I have verified that the data does indeed change... not in the decode but by putting a breakpoint and looking into the data in the ArrayDouble

**Comment by shroffk** [comment]
I will try the above

**Comment by shroffk** [comment]
>> assumes it's the same as long as the array itself is the same. 

Was this sarcastic :)
Anyway, as expected the creation of a new array addresses the above problem.

**Comment by kasemir** [comment]
Why would I be sarcastic?  An array VType consists not only of the array, but also time stamp, alarm, display info. IVDoubleArray.equals assumes equality just based on the array, not checking time stamp etc.
Anyway, thanks for finding and fixing the PVA client issue.

**Comment by shroffk** [comment]
Oh no no...It does check all of those. Which is why when I played around with new timestamp the updates started coming.

That is part of the VNumberArray.
```
	if (obj instanceof VNumberArray) {
            VNumberArray other = (VNumberArray) obj;
        
            return getClass().equals(other.getClass()) &&
                    getData().equals(other.getData()) &&
                    getAlarm().equals(other.getAlarm()) &&
                    getTime().equals(other.getTime()) &&
                    getDisplay().equals(other.getDisplay());
        }
        
```

The data part is where we were running into trouble...

```
getData().equals(other.getData()) &&
```
In the above case all the rest were the same and only the array data was different.

**Comment by kasemir** [comment]
OK, so we're overall good, thanks!
