### ISSUE TITLE
Confirm Message for Action button 

### ISSUE THREAD

**Issue by tanviash** [shroffk/phoebus#1044]
Action button in Phoebus does not ask the confirm message:
![ActionButton](https://user-images.githubusercontent.com/38105093/71688103-3dd0ca00-2d6d-11ea-9d63-5f59642bbec1.png)

**Comment by kasemir** [comment]
BOY supported a confirmation message on individual actions.
The Display Builder supports similar confirmation messages, but on the Action Button.

I can update the compatibility code such that when opening an *.opi action button where the action has a confirmation message, that's transferred into the button settings, so in the end pressing the button will again prompt for the same confirmation message.
Can you attach a simple example *.opi with just one button and the above action?

**Comment by tanviash** [comment]
@kasemir Here is the file that has the Action Button widget. Search for "Reset the crate".
[confirm-message-opi.txt](https://github.com/shroffk/phoebus/files/4037137/confirm-message-opi.txt)

**Comment by kasemir** [comment]
This should now work, try with the latest

**Comment by kasemir** [comment]
Close?
