### ISSUE TITLE
Liberation font installation unpredictable 

### ISSUE THREAD

**Issue by georgweiss** [shroffk/phoebus#1093]
The CommonFonts.install method installs Liberation fonts, but this does not always give the wanted result. 
Example 1:
1) Launch Phoebus without any tabs besides file browser.
2) Add a label to an existing or new display.
3) Select the font picker to launch the dialog.
4) The Liberation font family may be missing in the list, probably due to race conditions (that I have not investigated in depth). This becomes confusing if a class is used that defines precisely that font since the font dialog cannot show the association.
Example 2:
1) Launch Phoebus without any tabs besides file browser.
2) Start the data browser.
3) The label (y axis) font is expected to be Liberation (as defined in Model.java), but is not as CommonFonts.install has not been called. A fallback font is used instead, but this will of course be different depending on OS and maybe also OS version.

All in all CommonFonts.install should be called once at some point early in the Phoebus application startup phase. We could do it the way ESS installs custom fonts, i.e. separate application with this sole purpose.

**Comment by kasemir** [comment]
I'll extract the Liberation fonts into a separate 'application'.
