### ISSUE TITLE
"Transparent" Property for Group Widget

### ISSUE THREAD

**Issue by pavel-ch** [shroffk/phoebus#110]
For my tests with Display Builder on Phoebus, I need this "Transparent" Property for Group Widget.
As I have understood, you are going to be compatible with BOY, where this property is available.
I tried to add it.
Hope this can be usefull for you, too.
And generally, I hope that some small contributions from "public" are not unwanted.
Pull request follows.

**Comment by kasemir** [comment]
Thanks, has also been imported in the Eclipse-based Display Builder.
