### ISSUE TITLE
File/Open handling when there are multiple options

### ISSUE THREAD

**Issue by kasemir** [shroffk/phoebus#117]
When File/Open is called for *.opi or *.bob files, which can be handled by both the display editor and runtime, the user currently gets a dialog to select the desired tool, which gets old.

Ideas:

**Default application**
Make one of the applications a 'default', in this example the display runtime.
So File/Open *.opi will always open the display runtime, from where one can use the context menu to open the display in the editor.

**File/Open With**
In _addition_ to the default handling, add menu File/Open With that will present the dialog for selecting a tool. So File/Open *.opi will get the runtime, File/Open With prompts for editor or runtime.

**File/Open With updates the default application**
.. as in RCP. After Open With was invoked to open in editor, File/Open will now default to editor.
For control room or beam line this is probably a bad idea, because what a user gets from File/Open depends on what the _previous_ user did via File/Open With..

**Magically know what the user really wants**
Best, but unclear how to implement.

**Comment by pavel-ch** [comment]
Opinion:
Default application - definitely yes. Allow setting.ini to set one (technician sets opi editor in his workspace/computer, operator workstation has the runtime set as default)
File/Open With - yes to allow to use a non-default app
File/Open With updates the default application - for me impractical, does not work well, I hate it in RCP
Magically know what the user really wants - no idea

**Comment by kasemir** [comment]
I think we agree on all: Open With .. to give choice, plain open to use a default.
Yes, using the last "open with" to update the default as in RCP has been a bother to me as well.
I had originally thought that the default is mostly static. An application would declare itself the "default".
But I like your idea of making that a preference, so that's what it now is.
Originally set to use the "*run*" type application, but can be changed to "*edit*" for those who mostly create displays.
