### ISSUE TITLE
Support opening standalone web browser from top_resources

### ISSUE THREAD

**Issue by kasemir** [shroffk/phoebus#126]
Need to somehow support opening standalone web browser from top_resources.
This way, links to web pages can be added to the File/Top Resources.

Should end up calling `javafx.application.HostServices.showDocument()`, i.e. open the usual web browser, outside of the Java app.
Could be implemented directly in `PhoebusApplication.createTopResourcesMenu()`. Maybe there's also an advantage in implementing this via an `AppDescriptor`, in which case resources might require the form `http://path/to/page?app=that_new_app_which_starts_external_web_browser`.

**Comment by shroffk** [comment]
I think implementing this as an app might be a good idea.

The app would contribute a menu item to the top menu...additionally we could have the app support all actions of opening webpages (e.g. a context action on a alarm)

**Comment by kasemir** [comment]
Implemented app=web, which launches the normal web browser, with example top_resources entry
