### ISSUE TITLE
Windows platform: Open Display action not working correctly

### ISSUE THREAD

**Issue by pavel-ch** [shroffk/phoebus#130]
To resolve this, a tweak in DisplayInfo.toURI() is necessary.
Tried to solve in #129 but have got a test failure. Looking for a working solution.
If you have a quick solution @kasemir I would appreciate a hint. You have already solved that somewhere but I cannot locate the right place.

**Comment by pavel-ch** [comment]
Improved by #131, passes test and works for me on Windows and Linux

**Comment by pavel-ch** [comment]
Added a test in #132 

> Could you add something to DisplayInfoTest for the "C:..." type path that caused problems on windows?

**Comment by kasemir** [comment]
> works for me on Windows and Linux

Good, closing issue
