### ISSUE TITLE
File Browser

### ISSUE THREAD

**Issue by kasemir** [shroffk/phoebus#135]
Desired functionality (still open to discussion) and progress on the file browser introduced in #134:

 * [x] Browse files
 * [x] Context menu to "Open" file in appropriate app
 * [x] Allow selecting app if there's more than one
 * [x] Preference for setting the initial root directory for new file browsers
 * [x] Show error when file can't be opened in dialog (in addition to the current log message)
 * [x] Context menu to "Open With" to pick app
 * [x] Double-click to "Open"
 * [x] Allow opening in external tool
 * [x] Icon of the (default) application
 * [x] Allow opening file in text editor (is that just one of the external tools?)
 * [x] Save/restore state. AppResourceDescriptor with create(URL) so that it allows opening navigator for directory, keeping that as the file:// resource which is saved/restored on restart? Or use memento for the URL? Or use AppResourceDescriptor for URL, plus memento for the currently selected file, expanding file tree to that on restart?
 * [x] Hide 'hidden' files based on `File.isHidden()`
 * [x] Context menu: Rename files
 * [x] Context menu: Delete files
 * [x] Context menu: Create new directory
 * [x] Context menu: Copy/paste/duplicate files
 * [x] Context menu: Refresh
 * [x] Allow 'dropping' files from outside to copy or move them into the target directory
 * [x] Context menu: Show/edit properties (executable, read-only, limited to what's supported by NIO package for all operating systems)?
 * [x] Copy full path of file to clipboard (so can then use 'chmod' etc. in terminal)
 * [x] Watch file system and refresh display as files are added/removed/renamed

**Comment by kasemir** [comment]
Already works quite well, so far no performance issues when browsing files!

Small layout issue in the top row on Linux, where label and button are too narrow:
![fb](https://user-images.githubusercontent.com/1932421/37605135-f599f89a-2b68-11e8-97bf-164b1a22a5b2.png)

**Comment by shroffk** [comment]
Ok...I can clean that up

The double click open is also implemented...it opens using the default app or prompts the user to select an app when multiple apps can handle the selected file.

**Comment by kasemir** [comment]
Regarding double-click, I think it should be like File/Open: If there are multiple apps, it uses the preference to pick the default. (See use of `Preferences.default_apps` in `PhoebusApplication`.(

Right now double-click is like File/Open With:  If there are multiple apps, it prompts. You can already to that via the context menu, Open With. The double click should be the fastest possible operation, using the Preferences.default_apps, or the first one found, never prompting.

**Comment by kasemir** [comment]
File browser works nicely when in a "Locked" (frozen) pane: Double-clicking on a file opens the tab in the next non-frozen pane.

![filebrowser](https://user-images.githubusercontent.com/1932421/42113897-0315233a-7bbb-11e8-85e3-e1b8838aab07.png)

**Comment by kasemir** [comment]
Here's a layout in code as opposed to FXML what resizes properly without cutting the label and button in the top row:

```
Label label = new Label("Base Directory:");
TextField path = new TextField();
Button browse = new Button("Browse");

label.prefHeightProperty().bind(path.heightProperty());
HBox.setHgrow(path, Priority.ALWAYS);
HBox toolbar = new HBox(5.0, label, path, browse);

TreeView<File> tree = new TreeView<>();

BorderPane layout = new BorderPane(tree);
toolbar.setPadding(new Insets(0, 0, 5, 0));
layout.setTop(toolbar);
layout.setPadding(new Insets(5.0));
```

![layout](https://user-images.githubusercontent.com/1932421/42183646-aa7cf81c-7e10-11e8-8e4c-f9be3d08f03d.png)

No idea how to express that in the FXML.

**Comment by kasemir** [comment]
Never mind, figured it out.

**Comment by kasemir** [comment]
Removing 'create new file', because we don't have a mechanism for creating the initial content.
For example, a new Data Browser *.plt is best created via Applications, Display, Data Browser and then saving it. Creating an empty *.plt file won't work.

All the other ideas listed have been implemented.
