### ISSUE TITLE
Picture and Symbol widgets not working

### ISSUE THREAD

**Issue by claudio-rosati** [shroffk/phoebus#158]
Picture and Symbol widgets are not able to display their default image (exception thrown):

```
java.io.FileNotFoundException: /icons/default_picture.png (No such file or directory)
```

or 

```
java.io.FileNotFoundException: /icons/default_symbol.png (No such file or directory)
```

The same happens when an image is D&D into the editor.

Moreover, for both widget, the file selector doesn't open, so no image can be selected in that way.

**Comment by kasemir** [comment]
In the old code, the Picture defaulted to `platform:/plugin/org.csstudio.display.builder.model/icons/default_picture.png`, and the Symbol to `platform:/plugin/org.csstudio.display.builder.model/icons/default_symbol.png`. Those Eclipse `platform` URLs obviously no longer work.
Meanwhile, a similar `examples:` path has been added for the display builder, and I've just updated the Picture and Symbol widgets to use that.
