### ISSUE TITLE
Cleanup Logbook Interfaces

### ISSUE THREAD

**Issue by shroffk** [shroffk/phoebus#204]
@es-sns121 
Cleanup the logbook interfaces. 
- [x] Remove the extra methods, like `getlogbooknames()`, which were added for convenience before jdk8 streams
- [x] refactor org.phoebus.logging to org.phoebus.logbook, rename the core-logging module into core-logbook
- [x] some of the core interfaces have static factory method and some have builders...a common design pattern is needed.

**Comment by shroffk** [comment]
@es-sns121 @kasemir 
I have simplified the core interfaces of org.phoebus.logging
 - removed necessary methods no longer needed in java8
 - removed builder for all default implementations, except logEntry, and replaced them with static factory methods

**Comment by kasemir** [comment]
Pull request?
