### ISSUE TITLE
A common search pattern

### ISSUE THREAD

**Issue by shroffk** [shroffk/phoebus#257]
Multiple viewing applications like logbook, alarm history, channelfinder, etc provide a search field. It would be great if all these search fields followed some standard.
This should not be too difficult

cf query:
```
*SR*V* tags=sys element=vacuum
```

log query:
```
beam position logbooks=comissioning,fault tags=LOTO
```

alarm query:
```
*SR*V*I state=MAJOR_ACK
```

**Comment by kasemir** [comment]
A large group of users would be people who casually browse log entries. Most of the time, they open the tool. It shows log entries for the last day. User scrolls up and down.
Then one day user wants to look for something specific in the last 6 month. Having to learn a query syntax is too much at this point. A UI would be better, for example a dialog like this:

```
Start & End Time: ....  [Button for start/end time dialog]
Logbooks:  ... [Selectors as in the Create Log Entry dialog]
Tags    :  ... [Selectors as in the Create Log Entry dialog]
Title:    __words_to_look_for_in_title__
Body:     __words_to_look_for_in_body__
User:     __limit_search_to_entries_by_that_user___
                               [Cancel] [Search]
```

Similar for alarm history search dialog:
```
Start & End Time: ....  [Button for start/end time dialog]
Severity:  Combo for severity filter
PV:     __partial_PV_name___
                               [Cancel] [Search]
```
