### ISSUE TITLE
Context menu on tab: interchanged texts "Split Horizontally / Vertically"

### ISSUE THREAD

**Issue by pavel-ch** [shroffk/phoebus#286]
Minor bug:
In the pane Tab context menu, texts "Split Horizontally / Vertically" are interchanged against icon and functionality.
I do not send a PR because the procedure is too complex for such a small bug.

A suggestion:
for an empty unnamed Pane (just opened by split and considered unwanted later), it should be possible to "close" the pane manually (context menu), instead of the necessity to open or move a content Tab and close the tab or move content back, which is somehow tricky.

**Comment by kasemir** [comment]
How are they interchanged?

![split](https://user-images.githubusercontent.com/1932421/44532372-f6d6bd00-a6c0-11e8-97f8-f34065b776ba.png)

"Split Horizontally" creates a left and right section. The icon shows a two-column arrangement with left and right section.

"Split Vertically" creates an upper and lower section. The icon shows a two-row arrangement with an upper and lower section.


I'll look at a context menu for the empty pane to allow closing it.

**Comment by pavel-ch** [comment]
Ok I supposed having split line horizontal on "Split Horizontally". Just closing issue.

**Comment by shroffk** [comment]
> for an empty unnamed Pane (just opened by split and considered unwanted later), it should be possible to "close" the pane manually (context menu), instead of the necessity to open or move a content Tab and close the tab or move content back, which is somehow tricky.

+1 for this feature

**Comment by kasemir** [comment]
Yes, like that, too. It's been implemented.

**Comment by kasemir** [comment]
The split icons are some public domain Eclipse icons which show the arrangement plus there's stuff inside each panel. Is that stuff misleading, does it detract from the plain panel arrangement, so they would be more obvious like this?

![split](https://user-images.githubusercontent.com/1932421/44533395-72d20480-a6c3-11e8-9e4b-c13149b349a9.png)

**Comment by kasemir** [comment]
Even better: Shows 'stuff' in the left respectively top section that will contain the original content of the pane that's about to be split, and an empty right resp. bottom section.

![split](https://user-images.githubusercontent.com/1932421/44535606-6308ef00-a6c8-11e8-9a7b-076cb7e91ff6.png)
