### ISSUE TITLE
Feature Request: Source Control

### ISSUE THREAD

**Issue by DanielCuneo** [shroffk/phoebus#294]
Is there a way to use source control with a Phoebus / CSS installation ?
I'm guessing that all the configuration is kept in plain text XML files or something similar.

**Comment by kasemir** [comment]
Yes ,  config files, settings, mementos, display files can all be put into e.g. git

**Comment by kasemir** [comment]
For example, you create a file "settings.ini" as described in the online help, https://phoebus-doc.readthedocs.io/en/latest/preference_properties.html:
```
org.phoebus.pv.ca/addr_list=gateway.my.site.org 127.0.0.1

org.phoebus.framework.workbench/external_apps=Text Editor,txt|dat|py|ini|db|xml|xsl|css|cmd|sh|st|log|out|md,gedit; Image Viewer,png|jpg|gif|jpeg,eog; PDF Viewer,pdf,firefox

org.phoebus.email/mailhost=smtp.my.site.gov

org.phoebus.ui/top_resources=/path/to/my/start.opi, Start Page
```

and create a script that always starts your product with `-settings /path/to/my/settings.ini`.
That `settings.ini`, as well as displays like `start.opi` are all text files that you can (actually should) keep in git.

**Comment by DanielCuneo** [comment]
I was thinking that the .bob files are the most important. Am I misunderstanding ?

**Comment by kasemir** [comment]
Right, those are XML as well, and can be kept in git.
Their format is actually such that modifications to a display tend to only change the affected XML, so a "git diff" is often quite readable.
