### ISSUE TITLE
Channel Finder Configuration

### ISSUE THREAD

**Issue by kasemir** [shroffk/phoebus#311]
Channel finder registers for PV name completion, https://github.com/shroffk/phoebus/blob/master/app/channel/utility/src/main/resources/META-INF/services/org.phoebus.framework.spi.PVProposalProvider .

By default, it looks for a `https://localhost:8181/ChannelFinder` based on https://github.com/shroffk/phoebus/blob/master/app/channel/channelfinder/src/main/resources/config/channelfinder.properties 
If you don't have the service running, it results in `java.net.ConnectException` whenever entering a PV name, and the origin of these errors is not immediately obvious.

The channel finder should be configued with preferences as described in https://phoebus-doc.readthedocs.io/en/latest/preferences.html, using a file like `channelfinder_preferences.properties` so that the available settings with defaults and explanation can be included in the preference section of the manual, https://phoebus-doc.readthedocs.io/en/latest/preference_properties.html .

In addition, the channel finder PV proposal provider should allow for a way to disable it, for example by configuring it with an empty URL, to avoid the errors

**Comment by shroffk** [comment]
@kasemir can we close this
