### ISSUE TITLE
Application Toolbar

### ISSUE THREAD

**Issue by kasemir** [shroffk/phoebus#323]
The application toolbar currently contains
 * Dropdown for top resources (same as File/Top Resources)
 * Logging Config
 * PV Tree
 * Probe
 * File Browser
 * Greetings

Suggestions to Remove:

I suggest removing Greetings and Logging Config.
I'm OK with also removing PV Tree and Probe, only leaving Top Resources & File Browser.

Suggestions to Add:

We have a local suggestion to add the Saved Layouts, i.e. a dropdown for the content of Window/Saved Layouts, PLUS an extra button for the "Main" layout, to be configured via preference.

**Comment by shroffk** [comment]
> Suggestions to Remove:
> 
> I suggest removing Greetings and Logging Config.
> I'm OK with also removing PV Tree and Probe, only leaving Top Resources & File Browser.

Ok with removing all the above mentioned toolbar entries..
