### ISSUE TITLE
Fix springboot configuration for alarm-config-logger service

### ISSUE THREAD

**Issue by shroffk** [shroffk/phoebus#380]
- [x] fix shutdown of the kafka streams
 - [x] fix the closing of the executor pool
 - [x] suppress the spring banners
 - [x] fix blocking of service when started with help
 - [x] suppress the voluminous logs from kafka, spring-boot
 - [x] fix ant build

**Comment by shroffk** [comment]
@kasemir have the above issues been solved

**Comment by kasemir** [comment]
Builds and runs with ant, but now more extra log messages with #384.

Just noticed that I've been talking about the alarm-logger, the one that had pull requests, not the alarm-config-logger mentioned in the title..
