### ISSUE TITLE
Make probe display configurable

### ISSUE THREAD

**Issue by johnsinsheimer** [shroffk/phoebus#407]
If I probe a vacuum indicator PV, the display rounds to 0.  Caget with the same PV name shows the correct value in scientific notation.  See attachment.

![image](https://user-images.githubusercontent.com/30604888/48155426-f64dcb80-e298-11e8-9bed-c209fa304357.png)

**Comment by kasemir** [comment]
Well, it's difficult.

As you can see in your probe screenshot, that PV has been configured to use a format of "0.1", i.e. that record on the IOC has PREC=1 to request one digit after the dot.
Which is exactly what you get: "0.0".

You're basically asking us to ignore the PREC resp. format. Once we do that, the next person will complain: "I configured my record to use 1 digit for precision, and I expected the number 8e-8 to thus be displayed as '0.0', but ..."

**Comment by johnsinsheimer** [comment]
Oh, so maybe caget by default ignores precision?

**Comment by shroffk** [comment]
Ok, 
The default behaviour should be to respect the PREC

However, we could explore the ability to allow users to configure the precision and units they want to use...just like BOY. As a diagnostic tool, adding a few advance setting to the probe might be useful.

![image](https://user-images.githubusercontent.com/2111304/48157218-11223f00-e29d-11e8-8159-d26420b1cfca.png)

**Comment by kasemir** [comment]
Changed the title. Probe functions as designed, displaying numbers according to the display metadata provided by the PV. But in some cases it might be better to NOT use that display information. Regrettably, it's hard to magically figure out what the user might want to see. The best option would be a "Format" selector in Probe with options like "Default (use the meta data)", "Decimal", and "Engineering", with the latter two having a configurable precision.

**Comment by kasemir** [comment]
New format options allow selecting for example exponential notation with custom precision:

![probe](https://user-images.githubusercontent.com/1932421/49901667-cc576e00-fe2f-11e8-90f3-239592fcd4b8.png)

**Comment by johnsinsheimer** [comment]
Very nice!  Thanks!
