### ISSUE TITLE
Phoebus app: sim://ramp or sim://sine not going into alarm state

### ISSUE THREAD

**Issue by tanviash** [shroffk/phoebus#429]
I created some simulated pvs under my alarm tree. However these sim pvs don't seem to go into alarm state. On probing the pv through phoebus GUI, I can see its value varying between its range and alaso going into alarm range, but that doesn't change the status of pv to 'alarm'.

This is what my alarm server shell show about this pv.
/Accelerator/root > ls -all     
  1 : /Accelerator/root/sim:\/\/ramp [sim://ramp] - connected, VDouble[3.0, NONE(NONE) - None, 2018-11-14T20:43:26.338384Z] - annunciating - latching - Current: OK/None (3.0), 2018-11-14 15:43:26.338, Alarm: OK/OK (-5.0), 2018-11-14 15:27:43.338
![alarm](https://user-images.githubusercontent.com/38105093/48511507-e26c1180-e824-11e8-8941-1c3af36910c6.PNG)

**Comment by kasemir** [comment]
It's a side effect of the recent update to EPICS 7.0.2 vtype.

If you can still see them go into alarm in the GUI, that means you're not building the GUI off the latest master branch. I see no alarms on sim://sine, sim://ramp.  Only sim://intermittent disconnects periodically as designed and that results in an alarm.

I'll have to re-enable alarms on sim:// PVs.

**Comment by kasemir** [comment]
Found the culprit, the sim:// PVs always used `Alarm.none()`.

**Comment by tanviash** [comment]
Thanks Kay. I'll close the issue now.

**Comment by tanviash** [comment]
Hi Kay, After merging your recent changes 08817d7, I still do not see the sim pvs going into alarm state. It's just the sim://intermittent that goes into alarm state.

**Comment by kasemir** [comment]
Check if you rebuilt.

I just downloaded the latest build from https://controlssoftware.sns.ornl.gov/css_phoebus/ and sure enough the sim://sine PV again has alarm state:

![image](https://user-images.githubusercontent.com/1932421/48517699-1f400480-e835-11e8-892a-6a71267bc0b9.png)

**Comment by kasemir** [comment]
![image](https://user-images.githubusercontent.com/1932421/48517769-662dfa00-e835-11e8-8cc6-d86dfaf201ca.png)

**Comment by shroffk** [comment]
I can confirm...I checked out the master and the alarms are available.

**Comment by tanviash** [comment]
Thanks. It works. Closing this issue.
