### ISSUE TITLE
Font popover localization issue

### ISSUE THREAD

**Issue by pavel-ch** [shroffk/phoebus#448]
Trying to make localization of Display Builder Editor, I have found that Font popover (and expecting the same for Color popover) is not in the right locale, although the rest of texts in the Editor is localized as expected.
I suspect WidgetFontPopover.java line 46 being the problem - loads always  the default locale texts:
`final InputStream iStream = WidgetFontPopOver.class.getResourceAsStream("messages.properties");`
Should I try to resolve the issue or you have an idea right now?
By the way, some applications like Probe or File Browser have no `messages.properties` so far. Is there a plan to make it localizable?

**Comment by kasemir** [comment]
You're correct, it should use https://github.com/shroffk/phoebus/blob/master/core/framework/src/main/java/org/phoebus/framework/nls/NLS.java to fetch the localized messages, instead of loading a fixed filename.
Ideally, everything would be localized, it's just a matter of time.
If you can contribute some localization, that would be great.

**Comment by pavel-ch** [comment]
Ok, idea with filename is working, but I do not know if it suits to you.
Advantage: using fxml %keyword construct for localization.
WidgetFontPopover.java line 46 replaced by:
```
String fname = "messages_" + Locale.getDefault().getLanguage() + ".properties";
InputStream iStream = WidgetFontPopOver.class.getResourceAsStream(fname);
if (iStream == null)
{
    iStream = WidgetFontPopOver.class.getResourceAsStream("messages.properties");
}
```
How to combine fxml localization with your NLS class is unclear for me.

**Comment by kasemir** [comment]
How about you extract something like this into a new NLS method:
```
class NLS
{
  ..
  /** Get stream for messages
    *  Tries to open "messages_{LOCALE}.properties",
    *  falling back to generic "messages.properties" 
    *  @param clazz Class relative to which message resources are located
    *  @returns Stream for messages or null
    */
 public static InputStream getMessages(Class<?> clazz)
 {
            // First try "messages_de.properties", "messages_fr.properties", "messages_zh.properties", ...
            // based on locale
            String filename = "messages_" + Locale.getDefault().getLanguage() + ".properties";
            InputStream msg_props = clazz.getResourceAsStream(filename);

            // Fall back to default file
            if (msg_props == null)
            {
                filename = "messages.properties";
                msg_props = clazz.getResourceAsStream(filename);
            }

            if (msg_props == null)
                getLogger().log(Level.SEVERE, "Cannot open '" + filename  + "' for " + clazz.getName());
           return msg_props;
}
```

Then use that inside the existing NLS.initializeMessages() as well as WidgetFontPopover.java

**Comment by kasemir** [comment]
Also, even if you think messages_cs.properties would have a limited audience  - and you're right, I wouldn't be able to verify if any of those translations are correct  ;-)  -  simply by adding them you'd update probe and the file browser to support localization, which as you noticed they don't right now. So then the next person who wants to localize for a different language has an easier task.

**Comment by kasemir** [comment]
If you're interested in localizing the file browser, maybe you can also think about the file browser 'home directory' icon vs. the 'home display' icon in the toolbar, which are currently the same.
That's especially confusing when the file browser is placed on the left side, as was the common case with the Eclipse-based CS-Studio panel layout:

![image](https://user-images.githubusercontent.com/1932421/49222477-fb8acb80-f3a9-11e8-8bc2-98ef9a03b43e.png)

As explained by the tool tips, the 'home' button in the toolbar will "Navigate to the home display", configured via `org.phoebus.ui/home_display`, which defaults to the example display and would point to the 'start' display in a production setup.
The file browser 'home' button will "Revert to the default directory", configured via `org.phoebus.applications.filebrowser/default_root`, which defaults to $(user.home) and would point to for example a beamline data directory in a production setup.

In principle, that 'home' icon is fine, but it needs some change to indicate the different functionality. Maybe a 'home' with a 'display' vs. 'folder' in the lower right corner?

**Comment by pavel-ch** [comment]
Ok looking into this. For Probe etc. I supply standard English default messages, for sure :-). Give me few days, not only this task in my queue... I look into the icon, too, however I usually do not do too much bitmap graphics by myself.

**Comment by pavel-ch** [comment]
Would it be possible to use in Databrowser 3 a language neutral icon for time interval dialog button?
now: 
![time_range](https://user-images.githubusercontent.com/771816/50046824-6fb3b780-00aa-11e9-9ca8-a3b97ad98427.png)
Desired something like: 
![time_range2](https://user-images.githubusercontent.com/771816/50046834-81955a80-00aa-11e9-8236-006f9731dfce.png)
Or: 
![time_range3](https://user-images.githubusercontent.com/771816/50046838-8823d200-00aa-11e9-9fdc-787ca5a0bb3a.png)
I know the graphics could be better...
Thanks for an opinion/idea.

**Comment by kasemir** [comment]
Yes icons without text would be better

**Comment by pavel-ch** [comment]
Closing the issue for now.
May be referenced later when I find strings necessary to externalize in my product.

**Comment by kasemir** [comment]
Thanks for all the message gymnastics!
