### ISSUE TITLE
ClosedFileSystemException build error with latest Eclipse 2018-09 and OpenJDK 11

### ISSUE THREAD

**Issue by kasemir** [shroffk/phoebus#501]
Downloaded the current Eclipse IDE (2018-09). With openjdk-11, each build fails with a `ClosedFileSystemException`.

Found hints that this is a known bug, need to install "Java 11" support (Example:
https://stackoverflow.com/questions/52540355/eclipse-2018-09-goes-into-endless-build-loop-with-java-11-plugin-closedfilesyst )

Tried to install the Java 11 support in a few ways, but it fails, for example like then when using Help/Marketplace:

![image](https://user-images.githubusercontent.com/1932421/50043310-a30d2c80-003f-11e9-88cc-0123543480f4.png)

**Comment by berryma4** [comment]
2018-12 release will support java 11. Tycho 1.3, which supports java 11, was released yesterday.

**Comment by kasemir** [comment]
No such problem with the previous Eclipse Photon 4.8.

To build with java 11, there is the issue of JavaFX now being one of the dependencies.
Since it's OS-specific, on Windows that means adding this to `dependencies/phoebus-target/.classpath`:
```
       <classpathentry exported="true" kind="lib" path="target/lib/javafx-base-11-win.jar"/>
       <classpathentry exported="true" kind="lib" path="target/lib/javafx-base-11.jar"/>
       <classpathentry exported="true" kind="lib" path="target/lib/javafx-controls-11-win.jar"/>
       <classpathentry exported="true" kind="lib" path="target/lib/javafx-controls-11.jar"/>
       <classpathentry exported="true" kind="lib" path="target/lib/javafx-fxml-11-win.jar"/>
       <classpathentry exported="true" kind="lib" path="target/lib/javafx-graphics-11-win.jar"/>
       <classpathentry exported="true" kind="lib" path="target/lib/javafx-graphics-11.jar"/>
       <classpathentry exported="true" kind="lib" path="target/lib/javafx-media-11-win.jar"/>
       <classpathentry exported="true" kind="lib" path="target/lib/javafx-media-11.jar"/>
       <classpathentry exported="true" kind="lib" path="target/lib/javafx-swing-11-win.jar"/>
       <classpathentry exported="true" kind="lib" path="target/lib/javafx-web-11-win.jar"/>
```

On Linux or Mac it's similar but replacing "-win" with the respective OS.

**Comment by kasemir** [comment]
Also, some code that uses JavaFX didn't explicitly add JFX to the classpath. Fixed by exporting `phoebus-target` (which includes JFX) from `core-ui`, requiring only phoebus-target/.classpath to hold the OS-specifig JFX jar references.

**Comment by kasemir** [comment]
Finally, when using Java 11, it seems necessary to not only configure JDK 11 as the JDK in the Eclipse Java/JRE settings, but also to run Eclipse itself with JDK 11.
Otherwise it will all compile fine, but when launched the runtime won't initialize JFX.
