### ISSUE TITLE
Alarm Logger Service to capture enabling/disabling of alarms

### ISSUE THREAD

**Issue by tanviash** [shroffk/phoebus#506]
Currently, alarm logger logs acknowledging of alarms through alarm command messages. However, it is also needed that alarm logger logs enabling/disabling of alarms in addition to acknowledging/un-acknowledging of alarms.

**Comment by kasemir** [comment]
Enable/disable is a config change. The config topic will see an update with "enabled" set to false.

**Comment by shroffk** [comment]
yes, I plan to look into trying to expand the logger to listen to and parse these confing messages too
