### ISSUE TITLE
pva libraries not found by travis 

### ISSUE THREAD

**Issue by shroffk** [shroffk/phoebus#53]
@kasemir have the pva libraries been moved or deleted?

**Comment by kasemir** [comment]
No idea.

I haven't tried to use the pva libs. As long as the diirt VType is still the old one, the phoebus.pv only has the JCA code, not the PVA code.

**Comment by shroffk** [comment]
(http://epics.sourceforge.net/maven2/): Connection reset 
I think sourceforge is down

**Comment by kasemir** [comment]
Yes, has been since yesterday, at least when trying to read some spinx docs that are also hosted by SF I get "Network Error (tcp_error)..Web Server may be down, too busy, or experiencing other problems .."

**Comment by kasemir** [comment]
Was a network problem
