### ISSUE TITLE
Alarm-config-logger didn't log the config loaded through -import config.xml option

### ISSUE THREAD

**Issue by tanviash** [shroffk/phoebus#530]
When I passed config.xml to alarm server using -import option, config-logger didn't log the config. I already had alarm-server running as a service and then used -import option to import the config in a separate terminal.

**Comment by kasemir** [comment]
I've been using `alarm-server -import config.xml` while the alarm server as well as the UI were running.
As far as I can tell, that worked OK.

The import would delete all the entries by adding 'null' messages to kafka, then add all the items from the config.xml.
The running server as well as the UI would follow along.

So what you see might be an issue limited to the config logger.
