### ISSUE TITLE
Public functions in org.phoebus.framework.autocomplete.MatchSegment

### ISSUE THREAD

**Issue by pavel-ch** [shroffk/phoebus#582]
Implementing own PVProposalProvider, I am subclassing the
`org.phoebus.framework.autocomplete.Proposal`
To do this, I need to make all variants of normal, match, comment functions `public` in `org.phoebus.framework.autocomplete.MatchSegment`, otherwise I cannot access these functions from my subclass.
Is it possible?

**Comment by kasemir** [comment]
That was an omission. Thanks for the pull request.
