### ISSUE TITLE
Probe / PV Name field should accept Drop PV Name

### ISSUE THREAD

**Issue by pavel-ch** [shroffk/phoebus#616]
A handy gesture would be to enable dropping PV Name from a widget (Ctrl/Drag) into an existing Probe instance, instead of creating a new Probe instance using context menu.

**Comment by pavel-ch** [comment]
At the moment, the Text field is set and the user has to press Enter key or click the Search button in Probe to get the actual value. Let me know if it is better to do it automatically in one step inside Drop event.

**Comment by kasemir** [comment]
Thanks for implementing the drop target.
Yes, I agree that dropping a PV should imply the 'Return', 'Search', do-it.
