### ISSUE TITLE
Cannot save *.bcf file

### ISSUE THREAD

**Issue by MaticPogacnik** [shroffk/phoebus#726]
Hi,

I am trying to create bcf file with predefined classes.
But when I try to save it i get an error that a file does not have suggested file extension. And I am unable to save it.

![bcferror](https://user-images.githubusercontent.com/5747624/60650202-f7dd8c80-9e43-11e9-9f6e-859b21ca9431.png)

It doesn't matter if I click Cancel or OK, either way I get dialog to select a name again and file is not saved.

Thanks,
Matic

**Comment by kasemir** [comment]
I can confirm that for now you'll need to save it as a *.bob file and then rename.
Will fix this next week.

**Comment by kasemir** [comment]
You can also try to fix this and submit a pull request.
At first glance, the required changes should be limited to the code around this section in https://github.com/shroffk/phoebus/blob/master/app/display/editor/src/main/java/org/csstudio/display/builder/editor/app/DisplayEditorInstance.java#L315:
```
 final File proper = ModelResourceUtil.enforceFileExtension(file, DisplayModel.FILE_EXTENSION);
```

Right now it always uses the *.bob `DisplayModel.FILE_EXTENSION`.
Should check `model.isClassModel()` to determine if maybe the bcf extension from 
`WidgetClassSupport.FILE_EXTENSION` is required.

**Comment by kasemir** [comment]
Thanks for finding this and then fixing it.
Please continue ;-)
