### ISSUE TITLE
Annotations "drifting"

### ISSUE THREAD

**Issue by mdavidsaver** [shroffk/phoebus#743]
More accurately, annotations not moving when plot data updates.  In the following plot the line moves up on successive updates.  I noticed that an annotation doesn't update until I click and drag.  Then it jumps back to the line.

![image](https://user-images.githubusercontent.com/4429215/61490417-bc71b080-a961-11e9-9330-b9d0b0154feb.png)

**Comment by kasemir** [comment]
True.
The annotations were first added to the data browser, looking at archived data.
Historic samples taken at some point in time tend to not change their value, which is why the annotations' values are only determined when an annotation is positioned, and not recomputed for each value update.

**Comment by mdavidsaver** [comment]
To be clear, this is a very minor issue for me.

**Comment by kasemir** [comment]
Understood. Same issue with the cursor markers, they only get values when moved.
Re-determining values of annotations and cursor markers on each value update (actually: graph redraw, could skip a few value updates) isn't free, so need to look at it some more when I find the time.

**Comment by kasemir** [comment]
Have an update that moves the annotation to the 'current' value.
It's great fun trying to 'grab' an annotation to adjust its position when it keeps moving up/down with the data.

**Comment by kasemir** [comment]
Annotations now move up/down with the data.
