### ISSUE TITLE
Cannot resolve imports in Appliance Archive

### ISSUE THREAD

**Issue by DorianHas** [shroffk/phoebus#748]
Hi there, !

My config :
- CentOs 7
- JDK 12
- Latest Phoebus version 
- Intellij 2019.1.3
- Eclipse 2019-06 (4.12.0)

Project import, from Maven in Eclipse and Intellij, went well so I tried to compile it. Some dependencies related to Appliance Archieve Reader cannot be resolved.

Fun fact, with maven comand lines, it works well. It might be something I missed during Maven import.

![Dependency issue](https://user-images.githubusercontent.com/51746537/61788966-bec98400-ae13-11e9-9226-3881f92290af.PNG)

Here's Intellij log :
[Issue Appliance Archive.txt](https://github.com/shroffk/phoebus/files/3426521/Issue.Appliance.Archive.txt)

Information:java: Errors occurred while compiling module 'app-databrowser'
Information:javac 12.0.1 was used to compile java sources
Information:Modules "app-display-convert-medm", "product" were fully rebuilt due to project configuration/dependencies changes
Information:24/07/2019 12:43 - Build completed with 97 errors and 36 warnings in 4 m 17 s 29 ms
T:\Phoebus\src\core\util\src\test\java\org\phoebus\util\time\TimeParserTest.java
    Warning:Warning:line (28)java: getInstant(java.lang.String) in org.phoebus.util.time.TimeParser has been deprecated
    Warning:Warning:line (39)java: parseDuration(java.lang.String) in org.phoebus.util.time.TimeParser has been deprecated
    Warning:Warning:line (42)java: parseDuration(java.lang.String) in org.phoebus.util.time.TimeParser has been deprecated
    Warning:Warning:line (46)java: parseDuration(java.lang.String) in org.phoebus.util.time.TimeParser has been deprecated
    Warning:Warning:line (49)java: parseDuration(java.lang.String) in org.phoebus.util.time.TimeParser has been deprecated
    Warning:Warning:line (52)java: parseDuration(java.lang.String) in org.phoebus.util.time.TimeParser has been deprecated
    Warning:Warning:line (72)java: parseDuration(java.lang.String) in org.phoebus.util.time.TimeParser has been deprecated
    Warning:Warning:line (75)java: parseDuration(java.lang.String) in org.phoebus.util.time.TimeParser has been deprecated
    Warning:Warning:line (116)java: parseDuration(java.lang.String) in org.phoebus.util.time.TimeParser has been deprecated
T:\Phoebus\src\core\framework\src\main\java\org\phoebus\framework\preferences\FileSystemPreferences.java
    Warning:Warning:line (720)java: Long(long) in java.lang.Long has been deprecated
T:\Phoebus\src\core\framework\src\main\java\org\phoebus\framework\preferences\FilePreferencesXmlSupport.java
    Warning:Warning:line (270)java: Integer(int) in java.lang.Integer has been deprecated
T:\Phoebus\src\core\framework\src\main\java\org\phoebus\framework\selection\SelectionUtil.java
    Information:Information:java: Some input files use unchecked or unsafe operations.
    Information:Information:java: Recompile with -Xlint:unchecked for details.
T:\Phoebus\src\app\logbook\ui\src\main\java\org\phoebus\logbook\ui\LogEntryTableApp.java
    Warning:Warning:line (46)java: canOpenResource(java.lang.String) in org.phoebus.framework.spi.AppResourceDescriptor has been deprecated
T:\Phoebus\src\app\logbook\ui\src\main\java\org\phoebus\logbook\ui\LogEntryCalenderApp.java
    Warning:Warning:line (46)java: canOpenResource(java.lang.String) in org.phoebus.framework.spi.AppResourceDescriptor has been deprecated
T:\Phoebus\src\app\logbook\ui\src\main\java\org\phoebus\logbook\ui\LogEntryTableViewController.java
    Information:Information:java: Some input files use unchecked or unsafe operations.
    Information:Information:java: Recompile with -Xlint:unchecked for details.
T:\Phoebus\src\app\logbook\inmemory\src\main\java\org\phoebus\applications\logbook\InMemoryLogClient.java
    Warning:Warning:line (225)java: findLogById(java.lang.Long) in org.phoebus.logbook.LogClient has been deprecated
    Warning:Warning:line (135)java: set(java.util.Collection<org.phoebus.logbook.LogEntry>) in org.phoebus.logbook.LogClient has been deprecated
T:\Phoebus\src\app\log-configuration\src\main\java\org\phoebus\applications\utility\LoggingConfiguration.java
    Information:Information:java: /T:/Phoebus/src/app/log-configuration/src/main/java/org/phoebus/applications/utility/LoggingConfiguration.java uses unchecked or unsafe operations.
    Information:Information:java: Recompile with -Xlint:unchecked for details.
T:\Phoebus\src\app\display\convert-medm\src\main\java\org\csstudio\utility\adlparser\fileParser\widgetParts\ADLConnected.java
    Warning:Warning:line (70)java: Integer(int) in java.lang.Integer has been deprecated
    Warning:Warning:line (71)java: Integer(int) in java.lang.Integer has been deprecated
T:\Phoebus\src\app\display\convert-medm\src\main\java\org\csstudio\utility\adlparser\fileParser\widgetParts\ADLObject.java
    Warning:Warning:line (219)java: Integer(int) in java.lang.Integer has been deprecated
    Warning:Warning:line (220)java: Integer(int) in java.lang.Integer has been deprecated
    Warning:Warning:line (221)java: Integer(int) in java.lang.Integer has been deprecated
    Warning:Warning:line (222)java: Integer(int) in java.lang.Integer has been deprecated
T:\Phoebus\src\app\display\convert-medm\src\main\java\org\csstudio\utility\adlparser\fileParser\widgetParts\ADLBasicAttribute.java
    Warning:Warning:line (153)java: Integer(int) in java.lang.Integer has been deprecated
    Warning:Warning:line (154)java: Integer(int) in java.lang.Integer has been deprecated
T:\Phoebus\src\app\display\convert-medm\src\main\java\org\csstudio\utility\adlparser\fileParser\widgetParts\ADLLimits.java
    Warning:Warning:line (38)java: Float(float) in java.lang.Float has been deprecated
    Warning:Warning:line (40)java: Float(float) in java.lang.Float has been deprecated
    Warning:Warning:line (42)java: Float(float) in java.lang.Float has been deprecated
T:\Phoebus\src\app\display\convert-medm\src\main\java\org\csstudio\utility\adlparser\fileParser\widgetParts\ADLPlotcom.java
    Warning:Warning:line (44)java: Integer(int) in java.lang.Integer has been deprecated
    Warning:Warning:line (45)java: Integer(int) in java.lang.Integer has been deprecated
T:\Phoebus\src\app\display\convert-medm\src\main\java\org\csstudio\utility\adlparser\fileParser\widgetParts\ADLPlotData.java
    Warning:Warning:line (39)java: Float(float) in java.lang.Float has been deprecated
    Warning:Warning:line (40)java: Float(float) in java.lang.Float has been deprecated
T:\Phoebus\src\app\display\convert-medm\src\main\java\org\csstudio\utility\adlparser\fileParser\widgetParts\ADLPen.java
    Warning:Warning:line (35)java: Integer(int) in java.lang.Integer has been deprecated
T:\Phoebus\src\app\display\convert-medm\src\main\java\org\csstudio\utility\adlparser\fileParser\widgets\ByteMonitor.java
    Warning:Warning:line (123)java: Integer(int) in java.lang.Integer has been deprecated
    Warning:Warning:line (124)java: Integer(int) in java.lang.Integer has been deprecated
T:\Phoebus\src\app\display\convert-medm\src\main\java\org\csstudio\utility\adlparser\fileParser\widgetParts\ADLPlotTrace.java
    Warning:Warning:line (32)java: Integer(int) in java.lang.Integer has been deprecated
T:\Phoebus\src\app\display\convert-medm\src\main\java\org\csstudio\utility\adlparser\fileParser\widgets\Arc.java
    Warning:Warning:line (106)java: Integer(int) in java.lang.Integer has been deprecated
    Warning:Warning:line (107)java: Integer(int) in java.lang.Integer has been deprecated
T:\Phoebus\src\app\databrowser\src\main\java\org\phoebus\archive\reader\appliance\ApplianceValueIterator.java
    Error:Error:line (10)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (11)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (12)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (38)java: package edu.stanford.slac.archiverappliance.PB.EPICSEvent does not exist
    Error:Error:line (39)java: package edu.stanford.slac.archiverappliance.PB.EPICSEvent does not exist
    Error:Error:line (40)java: package edu.stanford.slac.archiverappliance.PB.EPICSEvent does not exist
    Error:Error:line (53)java: cannot find symbol
  symbol:   class GenMsgIterator
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (54)java: cannot find symbol
  symbol:   class EpicsMessage
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (149)java: cannot find symbol
  symbol:   class EpicsMessage
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (227)java: cannot find symbol
  symbol:   class EpicsMessage
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (265)java: cannot find symbol
  symbol:   class PayloadInfo
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (105)java: cannot find symbol
  symbol:   class DataRetrieval
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (133)java: cannot find symbol
  symbol:   class EpicsMessage
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (150)java: cannot find symbol
  symbol:   class PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (154)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (155)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (156)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (157)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (158)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (162)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (166)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (171)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (172)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (179)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (193)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (194)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (209)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
    Error:Error:line (267)java: cannot find symbol
  symbol:   class FieldValue
  location: class org.phoebus.archive.reader.appliance.ApplianceValueIterator
T:\Phoebus\src\app\databrowser\src\main\java\org\phoebus\archive\reader\appliance\ApplianceArchiveReader.java
    Error:Error:line (22)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (23)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (24)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (25)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (190)java: cannot find symbol
  symbol:   class DataRetrieval
  location: class org.phoebus.archive.reader.appliance.ApplianceArchiveReader
    Error:Error:line (191)java: cannot find symbol
  symbol:   class RawDataRetrieval
  location: class org.phoebus.archive.reader.appliance.ApplianceArchiveReader
    Error:Error:line (257)java: cannot find symbol
  symbol:   class DataRetrieval
  location: class org.phoebus.archive.reader.appliance.ApplianceArchiveReader
    Error:Error:line (260)java: cannot find symbol
  symbol:   class GenMsgIterator
  location: class org.phoebus.archive.reader.appliance.ApplianceArchiveReader
    Error:Error:line (264)java: cannot find symbol
  symbol:   class EpicsMessage
  location: class org.phoebus.archive.reader.appliance.ApplianceArchiveReader
    Error:Error:line (291)java: cannot find symbol
  symbol:   class DataRetrieval
  location: class org.phoebus.archive.reader.appliance.ApplianceArchiveReader
    Error:Error:line (294)java: cannot find symbol
  symbol:   class GenMsgIterator
  location: class org.phoebus.archive.reader.appliance.ApplianceArchiveReader
    Error:Error:line (298)java: cannot find symbol
  symbol:   class EpicsMessage
  location: class org.phoebus.archive.reader.appliance.ApplianceArchiveReader
T:\Phoebus\src\app\databrowser\src\main\java\org\phoebus\archive\reader\appliance\ArchiverApplianceInvalidTypeException.java
    Error:Error:line (3)java: package edu.stanford.slac.archiverappliance.PB.EPICSEvent does not exist
    Error:Error:line (17)java: cannot find symbol
  symbol:   class PayloadType
  location: class org.phoebus.archive.reader.appliance.ArchiverApplianceInvalidTypeException
    Error:Error:line (25)java: cannot find symbol
  symbol:   class PayloadType
  location: class org.phoebus.archive.reader.appliance.ArchiverApplianceInvalidTypeException
    Error:Error:line (34)java: cannot find symbol
  symbol:   class PayloadType
  location: class org.phoebus.archive.reader.appliance.ArchiverApplianceInvalidTypeException
T:\Phoebus\src\app\databrowser\src\main\java\org\phoebus\archive\reader\appliance\ApplianceOptimizedValueIterator.java
    Error:Error:line (7)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (8)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (9)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (20)java: package edu.stanford.slac.archiverappliance.PB.EPICSEvent does not exist
    Error:Error:line (21)java: package edu.stanford.slac.archiverappliance.PB.EPICSEvent does not exist
    Error:Error:line (118)java: cannot find symbol
  symbol:   class PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceOptimizedValueIterator
    Error:Error:line (89)java: cannot find symbol
  symbol:   class DataRetrieval
  location: class org.phoebus.archive.reader.appliance.ApplianceOptimizedValueIterator
    Error:Error:line (90)java: cannot find symbol
  symbol:   class GenMsgIterator
  location: class org.phoebus.archive.reader.appliance.ApplianceOptimizedValueIterator
    Error:Error:line (93)java: cannot find symbol
  symbol:   class PayloadInfo
  location: class org.phoebus.archive.reader.appliance.ApplianceOptimizedValueIterator
    Error:Error:line (94)java: cannot find symbol
  symbol:   class EpicsMessage
  location: class org.phoebus.archive.reader.appliance.ApplianceOptimizedValueIterator
    Error:Error:line (119)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceOptimizedValueIterator
    Error:Error:line (119)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceOptimizedValueIterator
    Error:Error:line (119)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceOptimizedValueIterator
    Error:Error:line (120)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceOptimizedValueIterator
    Error:Error:line (120)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceOptimizedValueIterator
    Error:Error:line (125)java: cannot find symbol
  symbol:   class EpicsMessage
  location: class org.phoebus.archive.reader.appliance.ApplianceOptimizedValueIterator
    Error:Error:line (132)java: cannot find symbol
  symbol:   class PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceOptimizedValueIterator
    Error:Error:line (133)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceOptimizedValueIterator
T:\Phoebus\src\app\databrowser\src\main\java\org\phoebus\archive\reader\appliance\ApplianceStatisticsValueIterator.java
    Error:Error:line (7)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (8)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (9)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (18)java: package edu.stanford.slac.archiverappliance.PB.EPICSEvent does not exist
    Error:Error:line (30)java: cannot find symbol
  symbol:   class EpicsMessage
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
    Error:Error:line (31)java: cannot find symbol
  symbol:   class GenMsgIterator
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
    Error:Error:line (32)java: cannot find symbol
  symbol:   class EpicsMessage
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
    Error:Error:line (33)java: cannot find symbol
  symbol:   class GenMsgIterator
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
    Error:Error:line (34)java: cannot find symbol
  symbol:   class EpicsMessage
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
    Error:Error:line (35)java: cannot find symbol
  symbol:   class GenMsgIterator
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
    Error:Error:line (36)java: cannot find symbol
  symbol:   class EpicsMessage
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
    Error:Error:line (37)java: cannot find symbol
  symbol:   class GenMsgIterator
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
    Error:Error:line (68)java: cannot find symbol
  symbol:   class DataRetrieval
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
    Error:Error:line (137)java: cannot find symbol
  symbol:   class PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
    Error:Error:line (138)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
    Error:Error:line (139)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
    Error:Error:line (140)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
    Error:Error:line (141)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
    Error:Error:line (142)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
    Error:Error:line (146)java: cannot find symbol
  symbol:   class EpicsMessage
  location: class org.phoebus.archive.reader.appliance.ApplianceStatisticsValueIterator
T:\Phoebus\src\app\databrowser\src\main\java\org\phoebus\archive\reader\appliance\ApplianceMeanValueIterator.java
    Error:Error:line (7)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (8)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (9)java: package org.epics.archiverappliance.retrieval.client does not exist
    Error:Error:line (13)java: package edu.stanford.slac.archiverappliance.PB.EPICSEvent does not exist
    Error:Error:line (14)java: package edu.stanford.slac.archiverappliance.PB.EPICSEvent does not exist
    Error:Error:line (106)java: cannot find symbol
  symbol:   class PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceMeanValueIterator
    Error:Error:line (76)java: cannot find symbol
  symbol:   class DataRetrieval
  location: class org.phoebus.archive.reader.appliance.ApplianceMeanValueIterator
    Error:Error:line (77)java: cannot find symbol
  symbol:   class GenMsgIterator
  location: class org.phoebus.archive.reader.appliance.ApplianceMeanValueIterator
    Error:Error:line (80)java: cannot find symbol
  symbol:   class PayloadInfo
  location: class org.phoebus.archive.reader.appliance.ApplianceMeanValueIterator
    Error:Error:line (81)java: cannot find symbol
  symbol:   class EpicsMessage
  location: class org.phoebus.archive.reader.appliance.ApplianceMeanValueIterator
    Error:Error:line (107)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceMeanValueIterator
    Error:Error:line (108)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceMeanValueIterator
    Error:Error:line (109)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceMeanValueIterator
    Error:Error:line (110)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceMeanValueIterator
    Error:Error:line (111)java: cannot find symbol
  symbol:   variable PayloadType
  location: class org.phoebus.archive.reader.appliance.ApplianceMeanValueIterator

**Comment by kasemir** [comment]
You're missing `pbrawclient-0.0.8.jar` on the classpath.
The file is in dependencies/install-jars/lib/pbraw/pbrawclient-0.0.8.jar .

```
mvn clean verify  -f dependencies/pom.xml
```
collects all dependencies into `dependencies/phoebus-target/target/lib`, from which the `ant` and `eclipse` setups get their dependencies.

**Comment by shroffk** [comment]
Hi, 
The pbraw library is not available in maven so we have to manually install it.
https://github.com/shroffk/phoebus/tree/master/dependencies/install-jars
The above project does just that...you can try to run the install on the it and see if intellij picks up the newly installed pbraw library

**Comment by shroffk** [comment]
I should ask murali if he is willing to publish this library and save us this confusion.

**Comment by DorianHas** [comment]
Perfect ! adding it to classpath solved the issue
