### ISSUE TITLE
JDBC Urls

### ISSUE THREAD

**Issue by DorianHas** [shroffk/phoebus#766]
Hi there,

We are using the following Url for the Databrowser: jdbc:mysql:replication://master,slave:port/bdd
RDBInfo only accepts :  jdbc:mysql://something

So I deleted "//" from JDBC Strings in RDBInfo java class to take account MySQL, Postgree and Oracle options :

![Capture](https://user-images.githubusercontent.com/51746537/62855273-14e26680-bcf2-11e9-9f8a-097fbc938bf6.PNG)

**Comment by kasemir** [comment]
Thanks for spotting this, will soon be fixed.

**Comment by kasemir** [comment]
Has been updated as you suggested, thanks!
