### ISSUE TITLE
Alarm Config Logger - Remote git not updating

### ISSUE THREAD

**Issue by tanviash** [shroffk/phoebus#800]
@shroffk Hi Kunal, Remote git is not updating with config changes with the latest code. Config.xml updates but then repo itself doesn't create new nodes and PV hierarchy underneath.

**Comment by shroffk** [comment]
Hi Tanvi, 
Were you able to get any error messages from phoebus?
Also, I remember adding a preference to enable/disable pushing to remote repo...can you check if the preference is correctly set.

**Comment by tanviash** [comment]
@shroffk I can look for logs and send it to you. What is the new preference setting called for enable/disable pushing to remote? I can't find it.

**Comment by tanviash** [comment]
Yes, we only use remote location to enable pushing to remote when a value is provided. Moreover, I see config.xml on remote getting updated but the directories inside the git repo do not update.

**Comment by shroffk** [comment]
and... I remember you saying that you tried to wipe out the old repo and started from a fresh one and still had the problem

**Comment by tanviash** [comment]
Yes, I manually deleted the old directories from the repo.

**Comment by shroffk** [comment]
Ok, I will wipe out and try a fresh installation myself... if you can find error logs or messages that would be very helpful
