### ISSUE TITLE
Misleading "No Alarm Server Connection"

### ISSUE THREAD

**Issue by georgweiss** [shroffk/phoebus#862]
The alarm views are showing No Alarm Server Connection even though the configuration obviously has been read from the alarm server (see screen shot). I guess this is because none of the PVs in the configuration is sending any data. Not sure if that defines a corner case, but as messages go, I think this one is misleading.

**Comment by kasemir** [comment]
Reading the alarm configuration from Kafka and having a connection to the alarm server to get updates on the current state are two different things.

Technically, the message appears if there have been no state updates from the alarm server for a while, which means there have been no actual state changes nor any 'idle' messages which are sent periodically in the absence of real state changes. 

No alarm server connection means that there's no alarm server. You're looking at a static setup, you won't get any alarms, no annunciations, you cannot acknowledge alarms.

**Comment by georgweiss** [comment]
OK, I think I understand this better now. However, to me it seems there is a difference to BEAST. When user changes config in for instance the alarm tree, the alarm server is - as far as I can determine - not triggered to change its configuration. The -config switch is used to select configuration at alarm server startup, but a change in the UI does not affect server. The UI will read configuration from Kafka, but not the server it seems. Hence my problems understanding the error message.
Or am I missing something?

**Comment by kasemir** [comment]
The server and the UI are separate in both the old and new implementation.

Either way, you start one or more alarm servers, each for a fixed configuration.
In the UI, you can select at runtime with which configuration you want to interact.
Changing the configuration in the UI does now start/stop/change servers.
If some item is configured for an automated action like sending email, that will happen as long as an alarm server is running for that configuration, no matter if some UI looks at it.

**Comment by kasemir** [comment]
Yes, you need to start one alarm server per configuration as a linux service.
I've tweaked the Readme, https://github.com/shroffk/phoebus/commit/5573ac3e1bb2bc24ff1be731b587a51a55dca48e#diff-7d665d42ffaa52128e933e818bd9ed80

**Comment by georgweiss** [comment]
OK, thanks.
