### ISSUE TITLE
core dependencies, specifically between types and logbook

### ISSUE THREAD

**Issue by kasemir** [shroffk/phoebus#900]
The 'core' dependencies currently look like this:

![core](https://user-images.githubusercontent.com/1932421/68314857-e2dc6880-0084-11ea-9017-afb8383f629c.png)

'types' is quite high in that dependency hierarchy and depends on logbook.
Other tools should be able to use the basic types without getting a logbook dependency, which in turn requires ui.
For example, if I try to add a context menu to the "PV List" tool in UI based on the selected PV, I'd need to add a dependency from ui to types, which creates a circle:

![core_issue](https://user-images.githubusercontent.com/1932421/68315237-76159e00-0085-11ea-9d6c-b9b3bc9b1c0f.png)

I suggest changing the dependencies such that logbook uses types, and not the other way around. So the adapter from logbook to PV moves to the logbook module:

![core_simple](https://user-images.githubusercontent.com/1932421/68315685-21beee00-0086-11ea-820c-0bc3a8e3899d.png)

This would allow ui to use types (so that PV list can have a PV-based context menu):

![core_fix](https://user-images.githubusercontent.com/1932421/68315545-eb816e80-0085-11ea-866b-c5ba8e045fc3.png)

**Comment by shroffk** [comment]
Ok,
I agree with this.

**Comment by kasemir** [comment]
#901
