### ISSUE TITLE
X/Y Plot - Hiding Traces broken

### ISSUE THREAD

**Issue by kingspride** [shroffk/phoebus#940]
Hi Kunal and Friends,

I have another Bug to report.

I want to hide all traces of an XY Plot  by default and only show them when the user checks a corresponding box.

I therefore disabled the property "visible" on all traces and wrote rules to manipulate it.

The result is: At start of the display, all traces are visible. I have to hide them at runtime.

![image](https://user-images.githubusercontent.com/45198837/68880313-50cf0280-070b-11ea-953d-eafbbb38d94d.png)

![image](https://user-images.githubusercontent.com/45198837/68880340-5d535b00-070b-11ea-84e2-7be5014f3771.png)

![image](https://user-images.githubusercontent.com/45198837/68880375-6d6b3a80-070b-11ea-9b05-70857a6cab5c.png)
![image](https://user-images.githubusercontent.com/45198837/68880386-73f9b200-070b-11ea-9ab7-c12d011ce22c.png)

**Comment by kasemir** [comment]
I can reproduce, will look into it.

**Comment by kasemir** [comment]
It's been fixed.

In your screenshot, the PVs used by the checkboxes appear to be invalid until you once toggle them.
If these are records on an IOC, add `field(PINI, "YES")`.
If these are local PVs, provide an initial value like `loc:\\show(0)`.

**Comment by kingspride** [comment]
thanks a lot!
