### ISSUE TITLE
RTYP field always "disconnected"

### ISSUE THREAD

**Issue by georgweiss** [shroffk/phoebus#950]
The RTYP field (being the record type name) is - when given as the PV name for a widget - considered as always disconnected. This is not the case for BOY displays in CS Studio/Eclipse, where the value is rendered as expected.

My guess would be the culprit is in DBRHelper.convertAlarm(), which returns Alarm.DISCONNECTED and that further up the call stack treats the entire PV as disconnected. 

A RTYP field I guess should be treated as some constant string and consequently an alarm status does not make sense.

Not sure about the solution, but I would possibly do:
`if (! (dbr instanceof STS))
            return Alarm.noValue()`

instead of

`if (! (dbr instanceof STS))
            return Alarm.disconnected()`

I need some help understanding the consequences of the above change.

**Comment by kasemir** [comment]
I'll look at it.
