### ISSUE TITLE
Rolling log file

### ISSUE THREAD

**Issue by georgweiss** [shroffk/phoebus#973]
Eclipse-based CS Studio supports a rolling log file concept. From what I can see, Phoebus does not. Any reason to not copy that concept?
Correct me if my assumption/conclusion is wrong.

**Comment by kasemir** [comment]
We primarily log via java.util.logging, where you can configure the FileHandler to roll, see 'limit' and 'count' options https://docs.oracle.com/javase/8/docs/api/java/util/logging/FileHandler.html

There may also be some console output that sneaks past the logging calls, for example if a script simply calls 'print'. Each site may handle that differently. We use a starter script that redirects stdout and stderr to a file, and you can then use Linux logrotate on that file.
